version: '3.7'
services:
  frontend:
    image: frontend
    build: ./frontend
    depends_on: 
      - backend

  backend: 
    image: backend
    build: ./backend
    environment:
      TEST_DATABASE_URI: $(TEST_DATABASE_URI)
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - database

  database:
    image: database
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on: 
      - frontend
  
